# This is a basic workflow to help you get started with Actions

name: Build and push the latest build to staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_push_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
 
      # Runs a set of commands using the runners shell
      - name: Build and push staging images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_NAME }}/contoso-website:latest
    
  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image 

    steps:
      - uses: actions/checkout@v2

      - name: Helm tool installer
        uses: Azure/setup-helm@v3
        with:
          # Version of helm
          version: 3.12.3

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1
        with:
          # Resource Group Name
          resource-group: mslearn-gh-pipelines-22635
          # AKS Cluster Name
          cluster-name: contoso-video
          # AKS Cluster Subscription
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Helm Deploy
        run: |
           helm upgrade \
            --install \
            --create-namespace \
            --atomic \
            --wait \
            --namespace staging \
            contoso-website \
            ./kubernetes/contoso-website \
            --set image.repository=${{ secrets.ACR_NAME }} \
            --set dns.name=${{ secrets.DNS_NAME }}
